@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Build.bat 
REM ===           Project: CT_ProjectConfig.ini 
REM ===  Project Filename: Libraries\CT_ProjectConfig.ini 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.83) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.83 
REM ===       Timestamp: 2025\10\01-23:57:02 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=X


REM =========================================================================

CT_Printf  -stdout "Building == CBolster - Libraries " 



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - BEFORE_SUB_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - BEFORE_SUB_PROJECTS



REM -------------------------------------------------------------------------
REM --- CBBase
IF NOT EXIST "CBBase"             GOTO SKIP_01_CBBASE 
IF NOT EXIST "CBBase\Build.bat"   GOTO SKIP_01_CBBASE 
PUSHD "CBBase" 
CALL  "Build.bat" 
POPD 
GOTO  FINISH_01_CBBASE
:SKIP_01_CBBASE
CT_Printf  -stdout "ERROR:  Missing SubProject -- CBBase 
:FINISH_01_CBBASE


REM -------------------------------------------------------------------------



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - AFTER_SUB_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - AFTER_SUB_PROJECTS



REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


