@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Clean.bat 
REM ===           Project: CBBase.vcproj 
REM ===  Project Filename: Libraries\CBBase\CBBase.vcproj 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.83) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.83 
REM ===       Timestamp: 2025\10\01-23:57:02 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=X


REM =========================================================================
REM === Do the Clean

CT_Printf       -stdout "Cleaning == CBolster - Libraries - CBBase " 


REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - PRE_CLEAN_FILES
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - PRE_CLEAN_FILES


CT_CleanVS .

IF EXIST "Win32_Debug"                                                            CT_Delete "Win32_Debug"                                                            
IF EXIST "Win32_Release"                                                          CT_Delete "Win32_Release"                                                          
IF EXIST "Win64_Debug"                                                            CT_Delete "Win64_Debug"                                                            
IF EXIST "Win64_Release"                                                          CT_Delete "Win64_Release"                                                          
IF EXIST "Generic_Debug"                                                          CT_Delete "Generic_Debug"                                                          
IF EXIST "Generic_Release"                                                        CT_Delete "Generic_Release"                                                        
IF EXIST "LinuxARM_Debug"                                                         CT_Delete "LinuxARM_Debug"                                                         
IF EXIST "LinuxARM_Release"                                                       CT_Delete "LinuxARM_Release"                                                       
IF EXIST "LinuxI32_Debug"                                                         CT_Delete "LinuxI32_Debug"                                                         
IF EXIST "LinuxI32_Release"                                                       CT_Delete "LinuxI32_Release"                                                       
IF EXIST "LinuxI64_Debug"                                                         CT_Delete "LinuxI64_Debug"                                                         
IF EXIST "LinuxI64_Release"                                                       CT_Delete "LinuxI64_Release"                                                       
IF EXIST "CBBase.aps"                                                             CT_Delete "CBBase.aps"                                                             
IF EXIST "CBBase.clw"                                                             CT_Delete "CBBase.clw"                                                             
IF EXIST "CBBase.suo"                                                             CT_Delete "CBBase.suo"                                                             
IF EXIST "CBBase.ncb"                                                             CT_Delete "CBBase.ncb"                                                             
IF EXIST "CBBase.vcproj.before.xml"                                               CT_Delete "CBBase.vcproj.before.xml"                                               
IF EXIST "CBBase.vcproj.after.xml"                                                CT_Delete "CBBase.vcproj.after.xml"                                                
IF EXIST "CBBase.vcproj.old"                                                      CT_Delete "CBBase.vcproj.old"                                                      
IF EXIST "CBBase.vcproj.*.user"                                                   CT_Delete "CBBase.vcproj.*.user"                                                   
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Win32.Debug.log"       CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Win32.Debug.log"       
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Win32.Release.log"     CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Win32.Release.log"     
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Win64.Debug.log"       CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Win64.Debug.log"       
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Win64.Release.log"     CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Win64.Release.log"     
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Generic.Debug.log"     CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Generic.Debug.log"     
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Generic.Release.log"   CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.Generic.Release.log"   
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxARM.Debug.log"    CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxARM.Debug.log"    
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxARM.Release.log"  CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxARM.Release.log"  
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxI32.Debug.log"    CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxI32.Debug.log"    
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxI32.Release.log"  CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxI32.Release.log"  
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxI64.Debug.log"    CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxI64.Debug.log"    
IF EXIST "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxI64.Release.log"  CT_Delete "..\..\Output\BuildLogs\CBolster_Libraries_CBBase.LinuxI64.Release.log"  


REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - PRE_UPDATE_TOOL
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - PRE_UPDATE_TOOL


CT_BuildUpdateTool -clean -linux .


REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - POST_UPDATE_TOOL
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - POST_UPDATE_TOOL


REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


